---
name: 'Deployment'
on:
  release:
    types:
      - 'published'

jobs:
  deploy:
    runs-on: 'ubuntu-20.04'
    steps:
      - name: 'Checkout'
        uses: 'actions/checkout@v2'
        with:
          submodules: true

      - name: 'Build & Deploy'
        env:
          DEPLOY_KEY: ${{ secrets.DEPLOY_KEY }}
          DEPLOY_USER: ${{ secrets.DEPLOY_USER }}
          DEPLOY_HOST: ${{ secrets.DEPLOY_HOST }}
        run: |
          # prepare ssh key
          ssh_key_dir=$(mktemp -d)
          echo "${DEPLOY_KEY}" > "${ssh_key_dir}/id_rsa"
          chmod 600 "${ssh_key_dir}/id_rsa"
          trap "rm -rf ${ssh_key_dir} || true" EXIT

          # load .env
          source .env

          # build and deploy
          docker run --rm \
            --volume "${ssh_key_dir}/id_rsa:/root/.ssh/id_rsa" \
            --volume "$(pwd):/srv" \
            --env GITHUB_SHA \
            --workdir /srv \
            hendrikmaus/blog-builder:${BLOG_BUILDER_VERSION} \
            deploy "${DEPLOY_USER}" "${DEPLOY_HOST}"

